# Generated by Django 5.0.6 on 2024-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
