# Generated by Django 5.0.6 on 2024-07-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0006_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
