# Generated by Django 5.1 on 2024-08-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0012_band_person_membership_band_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('product_secret_id', models.CharField(max_length=100)),
            ],
        ),
    ]
